Add check for Homebrew installation before updating packages

diff --git a/.chezmoiscripts/run_onchange_brew_bundle.sh.tmpl b/.chezmoiscripts/run_onchange_brew_bundle.sh.tmpl
--- a/.chezmoiscripts/run_onchange_brew_bundle.sh.tmpl
+++ b/.chezmoiscripts/run_onchange_brew_bundle.sh.tmpl
@@ -1,6 +1,11 @@
 #!/bin/bash
 
 # {{ include "brew/Brewfile" | sha256sum }}
+if ! command -v brew &> /dev/null
+then
+    echo "Homebrew not found, skipping brew bundle"
+    exit 0
+fi
 
 echo "Updating brew"
 brew update
